dependencies:
  config:
    - entity_browser.browser.image_browser
    - field.field.node.product.field_persona
content:
  field_product_image:
    type: entity_browser_file
    weight: 7
    region: content
    settings:
      entity_browser: image_browser
      field_widget_remove: true
      selection_mode: selection_append
      preview_image_style: focal_point_preview
      field_widget_edit: true
      field_widget_replace: true
      open: true
      view_mode: default
    third_party_settings: {  }
  field_product_image_more:
    type: entity_browser_file
    weight: 7
    region: content
    settings:
      entity_browser: image_browser
      field_widget_remove: true
      selection_mode: selection_append
      preview_image_style: focal_point_preview
      field_widget_edit: true
      field_widget_replace: true
      open: false
      view_mode: default
    third_party_settings: {  }
  field_persona:
    type: entity_reference_autocomplete
    weight: 101
    region: content
    settings:
      match_operator: CONTAINS
      match_limit: 10
      size: 60
      placeholder: ''
    third_party_settings: {  }
