dependencies:
  config:
    - field.field.node.product.field_persona
content:
  field_persona:
    type: entity_reference_autocomplete
    weight: 101
    region: content
    settings:
      match_operator: CONTAINS
      match_limit: 10
      size: 60
      placeholder: ''
    third_party_settings: {  }
