content:
  content_moderation_control:
    weight: 0
    region: content
    settings: {  }
    third_party_settings: {  }
  field_article_image:
    type: entity_reference_entity_view
    weight: 2
    region: content
    label: hidden
    settings:
      view_mode: medium_landscape
      link: false
    third_party_settings: {  }
