config_rewrite: replace
langcode: en
status: true
dependencies:
  config:
    - field.field.node.article.body
    - field.field.node.article.field_article_image
    - field.field.node.article.field_article_media
    - field.field.node.article.field_article_type
    - field.field.node.article.field_categories
    - field.field.node.article.field_display_author
    - field.field.node.article.field_meta_tags
    - field.field.node.article.field_tags
    - node.type.article
    - workflows.workflow.editorial
  enforced:
    module:
      - acquia_cms_article
  module:
    - content_moderation
    - field_group
    - media_library
    - metatag
    - path
    - scheduler
    - scheduler_content_moderation_integration
    - text
third_party_settings:
  field_group:
    group_media:
      children:
        - field_article_image
      parent_name: ''
      weight: 4
      format_type: fieldset
      region: content
      format_settings:
        id: ''
        classes: ''
        description: ''
        required_fields: true
      label: Media
    group_taxonomy:
      children:
        - field_categories
        - field_tags
        - field_article_type
      parent_name: ''
      weight: 5
      format_type: fieldset
      region: content
      format_settings:
        id: ''
        classes: ''
        description: ''
        required_fields: true
      label: Taxonomy
id: node.article.default
targetEntityType: node
bundle: article
mode: default
content:
  body:
    type: text_textarea_with_summary
    weight: 1
    settings:
      rows: 9
      summary_rows: 3
      placeholder: ''
      show_summary: false
    third_party_settings: {  }
    region: content
  created:
    type: datetime_timestamp
    weight: 7
    region: content
    settings: {  }
    third_party_settings: {  }
  field_article_image:
    type: media_library_widget
    weight: 6
    settings:
      media_types: {  }
    third_party_settings: {  }
    region: content
  field_article_type:
    weight: 10
    settings: {  }
    third_party_settings: {  }
    type: options_select
    region: content
  field_categories:
    weight: 8
    settings: {  }
    third_party_settings: {  }
    type: options_select
    region: content
  field_display_author:
    weight: 3
    settings:
      match_operator: CONTAINS
      match_limit: 10
      size: 60
      placeholder: ''
    third_party_settings: {  }
    type: entity_reference_autocomplete
    region: content
  field_meta_tags:
    type: metatag_firehose
    weight: 15
    region: content
    settings:
      sidebar: true
    third_party_settings: {  }
  field_tags:
    weight: 9
    settings:
      match_operator: CONTAINS
      match_limit: 10
      size: 60
      placeholder: ''
    third_party_settings: {  }
    type: entity_reference_autocomplete_tags
    region: content
  langcode:
    type: language_select
    weight: 2
    region: content
    settings:
      include_locked: true
    third_party_settings: {  }
  moderation_state:
    type: moderation_state_default
    weight: 9
    settings: {  }
    region: content
    third_party_settings: {  }
  path:
    type: path
    weight: 8
    region: content
    settings: {  }
    third_party_settings: {  }
  publish_on:
    type: datetime_timestamp_no_default
    weight: 11
    region: content
    settings: {  }
    third_party_settings: {  }
  publish_state:
    type: scheduler_moderation
    weight: 13
    region: content
    settings: {  }
    third_party_settings: {  }
  scheduler_settings:
    weight: 10
    region: content
    settings: {  }
    third_party_settings: {  }
  title:
    type: string_textfield
    weight: 0
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  translation:
    weight: 13
    region: content
    settings: {  }
    third_party_settings: {  }
  uid:
    type: entity_reference_autocomplete
    weight: 6
    settings:
      match_operator: CONTAINS
      size: 60
      placeholder: ''
      match_limit: 10
    region: content
    third_party_settings: {  }
  unpublish_on:
    type: datetime_timestamp_no_default
    weight: 12
    region: content
    settings: {  }
    third_party_settings: {  }
  unpublish_state:
    type: scheduler_moderation
    weight: 14
    region: content
    settings: {  }
    third_party_settings: {  }
  url_redirects:
    weight: 15
    region: content
    settings: {  }
    third_party_settings: {  }
hidden:
  field_article_media: true
  promote: true
  status: true
  sticky: true
