content:
  field_article_image:
    type: entity_reference_entity_view
    weight: 2
    region: content
    label: hidden
    settings:
      view_mode: x_large_super_landscape
      link: false
    third_party_settings: {  }
  field_display_author:
    type: entity_reference_entity_view
    weight: 4
    region: content
    label: hidden
    settings:
      view_mode: thumbnail
      link: false
    third_party_settings: {  }
