content:
  field_person_image:
    type: entity_reference_entity_view
    weight: 2
    region: content
    label: hidden
    settings:
      view_mode: thumbnail
      link: false
    third_party_settings: {  }
