dependencies:
  config:
    - field.field.node.person.field_meta_tags
  module:
    - metatag
content:
  field_meta_tags:
    weight: 31
    settings:
      sidebar: true
    third_party_settings: {  }
    type: metatag_firehose
    region: content
