-
  type: cohesion_content_templates
  export:
    uuid: 85770878-3db3-496a-8f7e-9bf9a0864576
    langcode: en
    status: true
    dependencies: {  }
    id: block_content_layout_canvas_full
    label: 'Full (Block_content, Layout canvas)'
    json_values: '{"canvas":[{"type":"container","uid":"drupal-field","title":"Field","status":{"collapsed":true},"uuid":"6ec7d334-8830-4d6e-b363-e772b1181395","parentUid":"root","isContainer":true,"children":[]}],"mapper":{"6ec7d334-8830-4d6e-b363-e772b1181395":{}},"model":{"6ec7d334-8830-4d6e-b363-e772b1181395":{"settings":{"title":"Layout canvas","settings":{"drupalField":""},"drupalField":"content.field_layout_canvas"},"context-visibility":{"contextVisibility":{"condition":"ALL"}},"styles":{"settings":{"element":"drupal-field"}}}},"previewModel":{"6ec7d334-8830-4d6e-b363-e772b1181395":{}},"variableFields":{"6ec7d334-8830-4d6e-b363-e772b1181395":[]},"meta":{"fieldHistory":[]}}'
    json_mapper: '{}'
    last_entity_update: entityupdate_0029
    modified: true
    selectable: true
    custom: false
    twig_template: block--cohesion--block-content-layout-canvas-full
    default: true
    entity_type: block_content
    bundle: layout_canvas
    view_mode: full
    master_template: __none__
