# Site Studio packages for df_tools_cohesion.
# Components
- config/dx8/cpt_banner_bar.package.yml
- config/dx8/cpt_drupal_block.package.yml
- config/dx8/cpt_hero_traditional.package.yml
- config/dx8/cpt_lift_slot.package.yml
# Templates
- config/dx8/block_content_layout_canvas_full.package.yml
