config_rewrite: replace
latest: dfs_one
enabled:
  dfs_one: dfs_one
safe:
  block_content: block_content
  media: media
  node: node
  taxonomy_term: taxonomy_term
  user: user
  menu_link_content: menu_link_content
types:
  block_content:
    - banner
    - hero
    - map
    - media
    - media_slideshow
    - text
  media:
    - image
  node:
    - article
    - event
    - landing_page
    - location
    - person
  user:
    - user
  menu_link_content:
    - main
author: AshRydell

