config_rewrite: replace
latest: dfs_one
enabled:
  dfs_one: dfs_one
safe:
  - block_content
  - media
  - menu_link_content
  - node
  - taxonomy_term
  - user
types:
  block_content:
    - banner
    - hero
    - map
    - media
    - media_slideshow
    - text
  media:
    - image
  node:
    - article
    - event
    - landing_page
    - location
    - person
  user:
    - user
  menu_link_content:
    - main
