language: php

sudo: false

php:
  - 5.6

matrix:
  fast_finish: true

env:
  matrix:
    - SCENARIO=none LIGHTNING=HEAD
    - SCENARIO=dfs_dev LIGHTNING=HEAD
    - SCENARIO=dfs_tec LIGHTNING=HEAD

# Cache Composer & Drush directories.
cache:
  bundler: true
  apt: true
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
    - "$HOME/.npm"

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  # Disable xdebug.
  - phpenv config-rm xdebug.ini
  # Update composer.
  - composer self-update
  - composer --version
  # Add the oauth token to prevent GitHub timeouts.
  - git config --global github.accesstoken $GITHUB_OAUTH_TOKEN

install:
  # Add Composer's local bin directory to the PATH so that we will be running
  # our installed versions of Drush, PHPCS, Behat, PhantomJS, etc.
  - export PATH="$HOME/.composer/vendor/bin:$TRAVIS_BUILD_DIR/bin:$PATH"

  # Composer install should fail on bad patches.
  - export COMPOSER_EXIT_ON_PATCH_FAILURE=1

  # MySQL Options
  - mysql -e 'SET GLOBAL wait_timeout = 5400;'
  - mysql -e "SHOW VARIABLES LIKE 'wait_timeout'"

  # PHP conf tweaks
  - echo 'max_execution_time = 120' >> drupal.php.ini;
  - echo 'sendmail_path = /bin/true' >> drupal.php.ini;
  - phpenv config-add drupal.php.ini
  - phpenv rehash

  # Test Lightning HEAD
  - if [[ "$LIGHTNING" == HEAD ]]; then composer require "drupal/lightning:dev-8.x-1.x" --no-update; fi

  # Build the DF code base.
  - composer global require phing/phing
  - phing build -Dversion=$VERSION -Dbranch=$TRAVIS_COMMIT

  # Install DF.
  - phing install -Ddb.database=drupal

  # If a scenario has been specified, enable it.
  - cd docroot
  - if [[ "$SCENARIO" != none ]]; then travis_wait drush es $SCENARIO; fi
  - cd ..

before_script:
  - cd docroot
  - drush runserver --default-server=builtin 8080 &>/dev/null &
  - phantomjs --webdriver=4444 > /dev/null &
  - sleep 5

script:
  - cd ./profiles/df
  - if [[ "$SCENARIO" == none ]]; then behat --strict --tags=df; fi
  - if [[ "$SCENARIO" != none ]]; then behat --strict --tags=$SCENARIO; fi
