-
  type: cohesion_content_templates
  export:
    uuid: 372ea852-3127-44ce-9b8c-be25bf4860e1
    langcode: en
    status: true
    dependencies: {  }
    label: Microsite
    id: ctn_tpl_microsite
    json_values: '{"canvas":[{"type":"container","uid":"drupal-field","title":"Field","status":{"collapsed":true},"uuid":"13f4912b-512b-4156-a36a-d054f3ad6ddb","parentUid":"root","isContainer":true,"children":[]}],"mapper":{"13f4912b-512b-4156-a36a-d054f3ad6ddb":{}},"model":{"13f4912b-512b-4156-a36a-d054f3ad6ddb":{"settings":{"title":"Layout canvas","settings":{"drupalField":""},"drupalField":"content.field_layout_canvas"},"context-visibility":{"contextVisibility":{"condition":"ALL"}},"styles":{"settings":{"element":"drupal-field"}}}},"previewModel":{"13f4912b-512b-4156-a36a-d054f3ad6ddb":{}},"variableFields":{"13f4912b-512b-4156-a36a-d054f3ad6ddb":[]},"meta":{"fieldHistory":[]}}'
    json_mapper: '{}'
    last_entity_update: entityupdate_0033
    modified: true
    selectable: true
    custom: true
    twig_template: node--cohesion--ctn-tpl-microsite
    default: false
    entity_type: node
    bundle: page
    view_mode: full
    master_template: mstr_tpl_microsite
-
  type: cohesion_master_templates
  export:
    uuid: 3e774913-e57b-4533-a595-a2c695674bef
    langcode: en
    status: true
    dependencies: {  }
    label: Microsite
    id: mstr_tpl_microsite
    json_values: '{"canvas":[{"type":"item","uid":"drupal-region","title":"Region","status":{"collapsed":true},"uuid":"ac656d50-4bd7-423e-8fc6-0e83e4268cf0","parentUid":"root","isContainer":false,"children":[]}],"mapper":{"ac656d50-4bd7-423e-8fc6-0e83e4268cf0":{}},"model":{"ac656d50-4bd7-423e-8fc6-0e83e4268cf0":{"settings":{"title":"Content region","region":{"theme":"cohesion_theme","type":"content"}},"context-visibility":{"contextVisibility":{"condition":"ALL"}},"styles":{"settings":{"element":"region"}}}},"previewModel":{"ac656d50-4bd7-423e-8fc6-0e83e4268cf0":{}},"variableFields":{"ac656d50-4bd7-423e-8fc6-0e83e4268cf0":[]},"meta":{"fieldHistory":[]}}'
    json_mapper: '{}'
    last_entity_update: entityupdate_0033
    locked: false
    modified: true
    selectable: true
    custom: null
    twig_template: page--cohesion--mstr-tpl-microsite
    default: false
