# Site Studio packages for df_tools_person.
# Content type templates
- config/dx8/node_person_content_browser.package.yml
- config/dx8/node_person_full.package.yml
- config/dx8/node_person_list.package.yml
- config/dx8/node_person_teaser.package.yml
- config/dx8/node_person_thumbnail.package.yml
