ui:
  video_display: hidden
  description_help: true
  details_save: true
  help_disabled: false
  dialog_disabled: true
  offcanvas_disabled: true
  promotions_disabled: true
  contribute_disabled: true
requirements:
  cdn: false
  bootstrap: false
  spam: false
