config_rewrite: replace
langcode: en
status: true
dependencies:
  config:
    - field.field.node.landing_page.body
    - field.field.node.landing_page.field_meta_tags
    - field.field.node.landing_page.layout_builder__layout
    - field.field.node.landing_page.layout_builder__translation
    - field.field.node.landing_page.layout_selection
    - node.type.landing_page
  module:
    - df_tools_layout
    - layout_builder
    - layout_builder_restrictions
    - layout_library
    - metatag
    - user
third_party_settings:
  layout_builder:
    allow_custom: true
    enabled: true
    sections:
      -
        layout_id: layouts_12
        layout_settings:
          gap: gap-md
          full_width: 0
          class: ''
        components:
          e7257fd8-9a0a-4977-bf82-9d0f14b3c64e:
            uuid: e7257fd8-9a0a-4977-bf82-9d0f14b3c64e
            region: content
            configuration:
              id: 'field_block:node:landing_page:title'
              label: Title
              provider: layout_builder
              label_display: '0'
              formatter:
                label: hidden
                type: string
                settings:
                  link_to_entity: false
                third_party_settings: {  }
              context_mapping:
                entity: layout_builder.entity
            additional: {  }
            weight: 0
            third_party_settings: {  }
        third_party_settings: {  }
  layout_library:
    enable: true
  layout_builder_restrictions:
    allowed_blocks: {  }
    allowed_layouts:
      - layouts_12
      - layouts_6_6
      - layouts_4_8
      - layouts_8_4
      - layouts_3_6_3
      - layouts_3-3-3-3
    entity_view_mode_restriction:
      allowed_blocks:
        AddToAny: {  }
        'Chaos Tools': {  }
        Content: {  }
        'Content fields':
          - 'field_block:node:landing_page:uid'
          - 'field_block:node:landing_page:created'
          - 'field_block:node:landing_page:body'
          - 'field_block:node:landing_page:title'
        'DF Tools Blocks': {  }
        'Entity Block': {  }
        'Entity Browser': {  }
        Help: {  }
        Menus: {  }
        'Moderation Dashboard': {  }
        'Responsive Preview': {  }
        System: {  }
        User: {  }
        'User fields': {  }
        core: {  }
      allowed_layouts: {  }
id: node.landing_page.default
targetEntityType: node
bundle: landing_page
mode: default
content:
  field_meta_tags:
    type: metatag_empty_formatter
    region: content
    weight: 1
    label: above
    settings: {  }
    third_party_settings: {  }
hidden:
  addtoany: true
  body: true
  content_moderation_control: true
  langcode: true
  layout_builder__layout: true
  layout_builder__translation: true
  layout_selection: true
  links: true
  search_api_excerpt: true

