<?php

/*
 * @file
 * Contains df_core.module.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_operation().
 */
function df_core_entity_operation_alter(array &$operations, EntityInterface $entity) {
  // Removes the clone operation from Entity clone for Access unpublished.
  $entityTypeId = $entity->getEntityTypeId();
  if ($entityTypeId == 'access_token') {
    unset($operations['clone']);
  }
}

/**
 * Implements hook_requirements().
 */
function df_core_requirements($phase) {
  $requirements = [];
  if ($phase == 'runtime') {
    $requirements['df_version'] = [
      'title' => t("Demo Framework"),
      'value' => t("7.0.6"),
      'description' => 'Last Update: 2023-11-16',
      'severity' => REQUIREMENT_INFO,
    ];
  }
  return $requirements;
}

/**
 * Implements hook_toolbar_alter().
 */
function df_core_toolbar_alter(&$items) {
  // Removes Toolbar Edit menut item.
  unset($items['contextual']);
}
