dependencies:
  config:
    - field.field.node.event.body
    - field.field.node.event.field_event_end_time
    - field.field.node.event.field_event_location
    - field.field.node.event.field_event_start_time
    - field.field.node.event.field_image
    - field.field.node.event.field_tags
    - field.field.node.event.field_type
    - node.type.event
  module:
    - text
    - user
id: node.event.default
targetEntityType: node
bundle: event
mode: default
content:
  body:
    label: hidden
    type: text_default
    weight: 101
    settings: {  }
    third_party_settings: {  }
    region: content
  field_event_end_time:
    weight: 106
    label: above
    settings:
      date_format: medium
      custom_date_format: ''
      timezone: ''
    third_party_settings: {  }
    type: timestamp
    region: content
  field_event_location:
    weight: 107
    label: above
    settings:
      link: true
    third_party_settings: {  }
    type: entity_reference_label
    region: content
  field_event_start_time:
    weight: 105
    label: above
    settings:
      date_format: medium
      custom_date_format: ''
      timezone: ''
    third_party_settings: {  }
    type: timestamp
    region: content
  field_image:
    weight: 102
    label: above
    settings:
      link: true
    third_party_settings: {  }
    type: entity_reference_label
    region: content
  field_tags:
    weight: 103
    label: above
    settings:
      link: true
    third_party_settings: {  }
    type: entity_reference_label
    region: content
  field_type:
    weight: 104
    label: above
    settings:
      link: true
    third_party_settings: {  }
    type: entity_reference_label
    region: content
  links:
    weight: 100
    settings: {  }
    third_party_settings: {  }
    region: content
hidden:
  addtoany: true
  langcode: true

