dependencies:
  config:
    - field.field.node.place.field_meta_tags
    - field.field.node.place.field_persona
    - field.field.node.place.field_place_hours
  module:
    - metatag
content:
  field_place_hours:
    type: text_textarea
    weight: 5
    region: content
    settings:
      rows: 5
      placeholder: ''
    third_party_settings: {  }
  field_meta_tags:
    weight: 31
    settings:
      sidebar: true
    third_party_settings: {  }
    type: metatag_firehose
    region: content
  field_persona:
    type: entity_reference_autocomplete
    weight: 32
    region: content
    settings:
      match_operator: CONTAINS
      match_limit: 10
      size: 60
      placeholder: ''
    third_party_settings: {  }
