content:
  field_place_image:
    type: entity_reference_entity_view
    weight: 0
    region: content
    label: hidden
    settings:
      view_mode: medium_landscape
      link: false
    third_party_settings: {  }
