config_rewrite: replace
langcode: en
status: true
dependencies:
  config:
    - core.entity_view_mode.media.medium_landscape
    - field.field.media.image.field_categories
    - field.field.media.image.field_tags
    - field.field.media.image.image
    - image.style.coh_medium_landscape
    - media.type.image
  enforced:
    module:
      - acquia_cms_image
  module:
    - image
id: media.image.medium_landscape
targetEntityType: media
bundle: image
mode: medium_landscape
content:
  image:
    type: image
    weight: 0
    region: content
    label: hidden
    settings:
      image_style: coh_medium_landscape
      image_link: ''
    third_party_settings: {  }
hidden:
  created: true
  field_categories: true
  field_tags: true
  langcode: true
  name: true
  search_api_excerpt: true
  thumbnail: true
  uid: true
