config_rewrite: replace
langcode: en
status: true
dependencies:
  config:
    - core.entity_view_mode.media.embedded
    - field.field.media.image.field_media_in_library
    - field.field.media.image.field_tags
    - field.field.media.image.field_unsplash_image_id
    - field.field.media.image.image
    - image.style.default_max
    - media.type.image
  module:
    - image
id: media.image.embedded
targetEntityType: media
bundle: image
mode: embedded
content:
  image:
    type: image
    weight: 0
    label: hidden
    settings:
      image_style: default_max
      image_link: ''
    third_party_settings: {  }
    region: content
hidden:
  addtoany: true
  created: true
  field_media_in_library: true
  field_tags: true
  field_unsplash_image_id: true
  langcode: true
  name: true
  search_api_excerpt: true
  thumbnail: true
  uid: true

