config_rewrite: replace
langcode: en
status: true
dependencies:
  config:
    - field.field.media.image.field_media_in_library
    - field.field.media.image.field_tags
    - field.field.media.image.field_unsplash_image_id
    - field.field.media.image.image
    - image.style.medium
    - media.type.image
  module:
    - focal_point
    - lightning_media
    - path
id: media.image.default
targetEntityType: media
bundle: image
mode: default
content:
  field_media_in_library:
    type: boolean_checkbox
    weight: 4
    settings:
      display_label: true
    third_party_settings: {  }
    region: content
  field_tags:
    weight: 5
    settings:
      match_operator: CONTAINS
      size: 60
      placeholder: ''
    third_party_settings: {  }
    type: entity_reference_autocomplete
    region: content
  field_unsplash_image_id:
    weight: 1
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
    type: string_textfield
    region: content
  image:
    type: image_focal_point
    weight: 2
    settings:
      preview_image_style: medium
      preview_link: true
      offsets: '50,50'
      progress_indicator: throbber
    third_party_settings:
      lightning_media:
        file_links: true
        remove_button: true
    region: content
  langcode:
    type: language_select
    weight: 3
    region: content
    settings:
      include_locked: true
    third_party_settings: {  }
  moderation_state:
    type: moderation_state_default
    weight: 100
    settings: {  }
    region: content
    third_party_settings: {  }
  name:
    type: string_textfield
    weight: 0
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
    region: content
  path:
    type: path
    weight: 6
    region: content
    settings: {  }
    third_party_settings: {  }
  status:
    type: boolean_checkbox
    settings:
      display_label: true
    weight: 7
    region: content
    third_party_settings: {  }
hidden:
  created: true
  uid: true

