image_browser:
  config:
    type: entity_imagebrowser
    dx8_imce_stream_wrapper: public
    dx8_entity_browser: image_browser
    cohesion_media_lib_types:
      - image
      - 0
      - 0
  content:
    type: entity_imagebrowser
    dx8_entity_browser: image_browser
    cohesion_media_lib_types:
      - image
      - 0
      - 0
