content:
  field_page_image:
    type: entity_browser_entity_reference
    weight: 3
    settings:
      entity_browser: media_browser
      field_widget_display: rendered_entity
      field_widget_display_settings:
        view_mode: medium_landscape
      field_widget_edit: true
      field_widget_remove: true
      selection_mode: selection_append
      field_widget_replace: false
      open: true
    region: content
    third_party_settings: {  }
