dependencies:
  module:
    - media_acquiadam
widgets:
  0988b202-0c87-492a-b044-ed326f274d88:
    settings:
      media_type: acquia_dam_asset
      submit_text: 'Select assets'
    uuid: 0988b202-0c87-492a-b044-ed326f274d88
    weight: 3
    label: 'Acquia DAM'
    id: acquiadam
