dependencies:
  module:
    - media_acquiadam
widgets:
  4ab011ef-8819-45e4-8dd7-d626b78ba81f:
    settings:
      media_type: acquia_dam_asset
      submit_text: 'Select assets'
    uuid: e41ec142-a492-4cc4-b11b-162b1906d936
    weight: 4
    label: 'Acquia DAM'
    id: acquiadam
