config_rewrite: replace
langcode: en
status: true
dependencies:
  config:
    - block_content.type.banner
    - entity_browser.browser.image_browser
    - field.field.block_content.banner.field_banner_image
    - field.field.block_content.banner.field_link
    - field.field.block_content.banner.field_summary
    - field.field.block_content.banner.field_title
  module:
    - entity_browser
    - link
id: block_content.banner.default
targetEntityType: block_content
bundle: banner
mode: default
content:
  field_banner_image:
    weight: 4
    settings:
      entity_browser: image_browser
      field_widget_remove: true
      open: true
      selection_mode: selection_append
      preview_image_style: thumbnail
      field_widget_edit: true
      field_widget_replace: false
      view_mode: default
    third_party_settings: {  }
    type: entity_browser_file
    region: content
  field_link:
    weight: 3
    settings:
      placeholder_url: ''
      placeholder_title: ''
    third_party_settings: {  }
    type: link_default
    region: content
  field_summary:
    weight: 2
    settings:
      rows: 5
      placeholder: ''
    third_party_settings: {  }
    type: string_textarea
    region: content
  field_title:
    weight: 1
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
    type: string_textfield
    region: content
  info:
    type: string_textfield
    weight: 0
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  langcode:
    type: language_select
    weight: 2
    region: content
    settings:
      include_locked: true
    third_party_settings: {  }
hidden: {  }
