config_rewrite: replace
langcode: en
status: true
dependencies:
  config:
    - core.entity_view_mode.media.hero
    - field.field.media.video.field_media_in_library
    - field.field.media.video.field_media_video_embed_field
    - media.type.video
  module:
    - layout_builder
    - video_embed_field
third_party_settings:
  layout_builder:
    sections: {  }
id: media.video.hero
targetEntityType: media
bundle: video
mode: hero
content:
  field_media_video_embed_field:
    type: video_embed_field_video
    weight: 0
    label: hidden
    settings:
      autoplay: true
      autoplayadmin: true
      loop: true
      mute: true
      controls: true
      responsive: true
      width: 854
      height: 480
      rel: false
    third_party_settings: {  }
    region: content
hidden:
  addtoany: true
  created: true
  field_media_in_library: true
  langcode: true
  name: true
  thumbnail: true
  uid: true
