content:
  field_event_image:
    type: entity_reference_entity_view
    weight: 0
    region: content
    label: hidden
    settings:
      view_mode: x_large_super_landscape
      link: false
    third_party_settings: {  }
