config_rewrite: replace
langcode: en
status: true
dependencies:
  module:
    - basic_auth
    - hal
    - node
    - serialization
    - user
id: entity.node
plugin_id: 'entity:node'
granularity: resource
configuration:
  methods:
    - GET
  formats:
    - hal_json
    - json
    - xml
  authentication:
    - basic_auth
    - cookie

