<?php
/**
 * @file
 * Install, update and uninstall functions for the DF installation profile.
 */

/**
 * Implements hook_install_tasks().
 */
function df_install_tasks(): array {
  $tasks = [];

  // Set system settings after install.
  $tasks['install_df_settings'] = [];

  // Install DF Tools Gin.
  $tasks['install_df_gin'] = [];

  return $tasks;
}

/**
 * The site name gets overwritten when the install configuration form is
 * submitted by Drush. We are using hook_install_tasks() to set values after
 * the form has been submitted.
 */
function install_df_settings() {
  $config_factory = \Drupal::configFactory();

  // Set theme settings.
  $config_factory
    ->getEditable('system.theme')
    ->set('default', 'olivero')
    ->set('admin', 'gin')
    ->save(TRUE);

  // Set site settings.
  $config_factory
    ->getEditable('system.site')
    ->set('name', "Demo Framework")
    ->set('mail', 'no-reply@example.com')
    ->save(TRUE);

  // Set node settings.
  $config_factory
    ->getEditable('node.settings')
    ->set('use_admin_theme', TRUE)
    ->save(TRUE);
}

/**
 * Install DF Tools Gin as part of install task.
 */
function install_df_gin() {
  $installer = \Drupal::service('module_installer');
  $installer->install(['df_tools_gin']);
}
