third_party_settings:
  better_formats:
    allowed_formats_toggle: 1
    allowed_formats:
      restricted_html: restricted_html
      basic_html: 0
      full_html: 0
    default_order_toggle: 0
    default_order_wrapper:
      formats:
        basic_html:
          weight: 0
        restricted_html:
          weight: 0
        full_html:
          weight: 1
