dependencies:
  config:
    - field.field.node.page.field_meta_tags
    - field.field.node.page.field_persona
  module:
    - metatag
content:
  body:
    weight: 3
    settings:
      rows: 9
      summary_rows: 3
      placeholder: ''
      show_summary: false
    third_party_settings: {  }
    type: text_textarea_with_summary
    region: content
  field_meta_tags:
    weight: 31
    settings:
      sidebar: true
    third_party_settings: {  }
    type: metatag_firehose
    region: content
  field_persona:
    type: entity_reference_autocomplete
    weight: 32
    region: content
    settings:
      match_operator: CONTAINS
      match_limit: 10
      size: 60
      placeholder: ''
    third_party_settings: {  }
