dependencies:
  config:
    - field.field.node.page.field_meta_tags
  module:
    - metatag
content:
  body:
    weight: 3
    settings:
      rows: 9
      summary_rows: 3
      placeholder: ''
      show_summary: false
    third_party_settings: {  }
    type: text_textarea_with_summary
    region: content
  field_meta_tags:
    weight: 31
    settings:
      sidebar: true
    third_party_settings: {  }
    type: metatag_firehose
    region: content
