<?php

/**
 * @file
 * Contains page_manager.module.
 */

/**
 * Implements hook_display_variant_plugin_alter().
 */
function page_manager_display_variant_plugin_alter(array &$definitions) {
  // Rename the core "Page with blocks" admin_label.
  $definitions ['block_page']['admin_label'] = t('Page with core blocks');

  // Sort the display variant plugins based on admin_label.
  asort($definitions);
}
