config_rewrite: replace
uuid: 1a187fae-3932-4161-b296-d64903a4c38f
langcode: en
status: true
dependencies:
  enforced:
    module:
      - media_library
  module:
    - focal_point
name: media_library
label: 'Media Library thumbnail (220x220)'
effects:
  327b8215-1aff-4190-8b3c-3574aa19230c:
    uuid: 327b8215-1aff-4190-8b3c-3574aa19230c
    id: focal_point_scale_and_crop
    weight: 2
    data:
      width: 220
      height: 220
      crop_type: focal_point

