config_rewrite: replace
uuid: 37ab782c-d651-4fb2-8d4f-2d22fe472ce5
langcode: en
status: true
dependencies:
  module:
    - focal_point
name: thumbnail
label: 'Thumbnail (100×100)'
effects:
  0303cd32-bc82-403f-91f6-f76c20df9a23:
    uuid: 0303cd32-bc82-403f-91f6-f76c20df9a23
    id: focal_point_scale_and_crop
    weight: 2
    data:
      width: 100
      height: 100
      crop_type: focal_point

