settings:
  file_directory: images
  file_extensions: 'png gif jpg jpeg'
  max_filesize: '510 KB'
  max_resolution: ''
  min_resolution: 85x85
  alt_field: false
  alt_field_required: false
  title_field: false
  title_field_required: false
  default_image:
    uuid: 707f9299-1474-4dae-a9da-d03a0fcca14c
    alt: 'A generic silhouette of a person.'
    title: ''
    width: 140
    height: 140
  handler: 'default:file'
  handler_settings: {  }
