config_rewrite: replace
_core:
  default_config_hash: A9npevXV2VkFRPDW0NRvhNx0X5XOufwpnY0bHsxU8j0
favicon:
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  use_default: true
third_party_settings:
  shortcut:
    module_link: true
preset_accent_color: blue
preset_focus_color: gin
enable_darkmode: '0'
classic_toolbar: horizontal
secondary_toolbar_frontend: true
high_contrast_mode: false
accent_color: ''
focus_color: ''
layout_density: default
show_description_toggle: false
rearrange_admin_menu_items: false
show_user_theme_settings: false
