config_rewrite: replace
langcode: en
status: true
dependencies:
  config:
    - core.entity_view_mode.node.full
    - field.field.node.landing_page.body
    - field.field.node.landing_page.field_layout_canvas
    - field.field.node.landing_page.field_meta_tags
    - node.type.landing_page
  module:
    - cohesion_elements
    - layout_builder
    - layout_builder_restrictions
    - layout_library
    - metatag
    - user
third_party_settings:
  layout_builder:
    allow_custom: false
    enabled: false
  layout_library:
    enable: false
  layout_builder_restrictions:
    entity_view_mode_restriction:
      allowed_blocks:
        Content: {  }
        'Content fields': {  }
        'Entity Browser': {  }
        Help: {  }
        'Lists (Views)': {  }
        Menus: {  }
        'Moderation Dashboard': {  }
        System: {  }
        User: {  }
        'User fields': {  }
        Views: {  }
        core: {  }
      allowed_layouts: {  }
id: node.landing_page.full
targetEntityType: node
bundle: landing_page
mode: full
content:
  field_layout_canvas:
    type: cohesion_entity_reference_revisions_entity_view
    weight: 0
    region: content
    label: hidden
    settings:
      view_mode: default
      link: false
    third_party_settings: {  }
  field_meta_tags:
    type: metatag_empty_formatter
    region: content
    label: hidden
    weight: 1
    settings: {  }
    third_party_settings: {  }
hidden:
  body: true
  content_moderation_control: true
  layout_builder__layout: true
  links: true
  search_api_excerpt: true
