config_rewrite: replace
langcode: en
status: true
dependencies:
  config:
    - field.field.node.landing_page.body
    - field.field.node.landing_page.field_layout_canvas
    - field.field.node.landing_page.field_meta_tags
    - field.field.node.landing_page.field_persona
    - field.field.node.landing_page.field_template_selector
    - node.type.landing_page
  module:
    - cohesion_elements
    - text
    - user
id: node.landing_page.default
targetEntityType: node
bundle: landing_page
mode: default
content:
  body:
    label: hidden
    type: text_default
    weight: 1
    settings: {  }
    third_party_settings: {  }
    region: content
  field_layout_canvas:
    type: cohesion_entity_reference_revisions_entity_view
    weight: 0
    region: content
    label: hidden
    settings:
      view_mode: default
      link: false
    third_party_settings: {  }
  links:
    weight: 2
    region: content
    settings: {  }
    third_party_settings: {  }
hidden:
  addtoany: true
  content_moderation_control: true
  field_meta_tags: true
  field_persona: true
  field_template_selector: true
  langcode: true
  search_api_excerpt: true
