config_rewrite: replace
status: true
dependencies:
  config:
    - field.field.node.landing_page.body
    - field.field.node.landing_page.field_layout_canvas
    - field.field.node.landing_page.field_meta_tags
    - field.field.node.landing_page.field_persona
    - field.field.node.landing_page.field_template_selector
    - field.field.node.landing_page.layout_selection
    - node.type.landing_page
    - workflows.workflow.editorial
  enforced:
    module:
      - dfs_inspace
  module:
    - cohesion_elements
    - cohesion_templates
    - content_moderation
    - metatag
    - path
    - text
id: node.landing_page.default
targetEntityType: node
bundle: landing_page
mode: default
content:
  body:
    type: text_textarea_with_summary
    weight: 2
    settings:
      rows: 5
      placeholder: ''
      summary_rows: 2
      show_summary: false
    third_party_settings: {  }
    region: content
  created:
    type: datetime_timestamp
    weight: 3
    settings: {  }
    third_party_settings: {  }
    region: content
  field_layout_canvas:
    type: cohesion_layout_builder_widget
    weight: 1
    settings: {  }
    third_party_settings: {  }
    region: content
  field_meta_tags:
    type: metatag_firehose
    region: content
    weight: 8
    settings: {  }
    third_party_settings: {  }
  field_persona:
    weight: 103
    settings: {  }
    third_party_settings: {  }
    type: options_select
    region: content
  field_template_selector:
    weight: 102
    settings: {  }
    third_party_settings: {  }
    type: cohesion_template_selector_widget
    region: content
  layout_selection:
    type: options_select
    region: content
    weight: 101
    settings: {  }
    third_party_settings: {  }
  moderation_state:
    type: moderation_state_default
    weight: 100
    settings: {  }
    region: content
    third_party_settings: {  }
  path:
    type: path
    weight: 4
    settings: {  }
    third_party_settings: {  }
    region: content
  status:
    type: boolean_checkbox
    weight: 10
    settings:
      display_label: true
    third_party_settings: {  }
    region: content
  title:
    type: string_textfield
    weight: 0
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
    region: content
  translation:
    weight: 10
    region: content
    settings: {  }
    third_party_settings: {  }
  uid:
    type: entity_reference_autocomplete
    weight: 2
    settings:
      match_operator: CONTAINS
      size: 60
      placeholder: ''
      match_limit: 10
    third_party_settings: {  }
    region: content
  url_redirects:
    weight: 50
    region: content
    settings: {  }
    third_party_settings: {  }
hidden:
  promote: true
  sticky: true
