config_rewrite: replace
langcode: en
status: true
dependencies:
  config:
    - core.entity_view_mode.node.teaser
    - field.field.node.landing_page.body
    - field.field.node.landing_page.field_layout_canvas
    - field.field.node.landing_page.field_meta_tags
    - node.type.landing_page
  module:
    - metatag
    - text
    - user
id: node.landing_page.teaser
targetEntityType: node
bundle: landing_page
mode: teaser
content:
  body:
    type: text_summary_or_trimmed
    weight: 0
    region: content
    label: hidden
    settings:
      trim_length: 600
    third_party_settings: {  }
  field_meta_tags:
    type: metatag_empty_formatter
    region: content
    weight: 2
    settings: {  }
    third_party_settings: {  }
    label: hidden
  links:
    weight: 1
    region: content
    settings: {  }
    third_party_settings: {  }
hidden:
  content_moderation_control: true
  field_layout_canvas: true
  search_api_excerpt: true
