config_rewrite: replace
export_list:
  block_content: block_content
  cohesion_layout: cohesion_layout
  component_content: component_content
  crop: crop
  file: file
  media: media
  menu_link_content: menu_link_content
  node: node
  shortcut: shortcut
  taxonomy_term: taxonomy_term
