permissions:
  - 'access component builder elements group'
  - 'access component content'
  - 'access components'
  - 'access content elements group'
  - 'access cpt_cat_accordion_components cohesion_component_category group'
  - 'access cpt_cat_background_media_contain cohesion_component_category group'
  - 'access cpt_cat_basic_components cohesion_component_category group'
  - 'access cpt_cat_card_components cohesion_component_category group'
  - 'access cpt_cat_dynamic_components cohesion_component_category group'
  - 'access cpt_cat_form_components cohesion_component_category group'
  - 'access cpt_cat_general_components cohesion_component_category group'
  - 'access cpt_cat_hero_components cohesion_component_category group'
  - 'access cpt_cat_image_and_media_componen cohesion_component_category group'
  - 'access cpt_cat_interactive_components cohesion_component_category group'
  - 'access cpt_cat_layout_components cohesion_component_category group'
  - 'access cpt_cat_map_components cohesion_component_category group'
  - 'access cpt_cat_read_more_components cohesion_component_category group'
  - 'access cpt_cat_search_engine cohesion_component_category group'
  - 'access cpt_cat_slider_components cohesion_component_category group'
  - 'access cpt_cat_tab_components cohesion_component_category group'
  - 'access cpt_cat_template_components cohesion_component_category group'
  - 'access cpt_cat_text_components cohesion_component_category group'
  - 'access cpt_cat_uncategorized cohesion_component_category group'
  - 'access custom elements group'
  - 'access drupal core elements group'
  - 'access elements'
  - 'access fields'
  - 'access form fields fields group'
  - 'access form help fields group'
  - 'access form layout fields group'
  - 'access helpers'
  - 'access hlp_cat_accordions cohesion_helper_category group'
  - 'access hlp_cat_dynamic_helpers cohesion_helper_category group'
  - 'access hlp_cat_general_helpers cohesion_helper_category group'
  - 'access hlp_cat_interactive_helpers cohesion_helper_category group'
  - 'access hlp_cat_landing_pages cohesion_helper_category group'
  - 'access hlp_cat_layout_helpers cohesion_helper_category group'
  - 'access hlp_cat_media_helpers cohesion_helper_category group'
  - 'access hlp_cat_page_sections cohesion_helper_category group'
  - 'access hlp_cat_sliders cohesion_helper_category group'
  - 'access hlp_cat_tabs cohesion_helper_category group'
  - 'access interactive elements group'
  - 'access layout elements group'
  - 'access media elements group'
  - 'access menu elements group'
  - 'access view elements group'
